# Generated by Django 5.2.5 on 2025-08-24 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_plus', models.PositiveIntegerField(default=0)),
                ('o_minus', models.PositiveIntegerField(default=0)),
                ('a_plus', models.PositiveIntegerField(default=0)),
                ('a_minus', models.PositiveIntegerField(default=0)),
                ('b_plus', models.PositiveIntegerField(default=0)),
                ('b_minus', models.PositiveIntegerField(default=0)),
                ('ab_plus', models.PositiveIntegerField(default=0)),
                ('ab_minus', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(limit_choices_to={'user_type': 'hospital'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('services', models.TextField(blank=True, help_text="Services offerts par l'hôpital")),
                ('opening_hours', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'hospital'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
