# Generated by Django 5.2 on 2025-08-29 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('completed', 'Terminé')], default='pending', max_length=20)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, help_text='Message au donneur')),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.bloodrequest')),
                ('donor', models.ForeignKey(limit_choices_to={'user_type': 'donor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('donor', 'blood_request')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('donation_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.donationresponse')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
