# Generated by Django 5.2 on 2025-10-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_bloodrequest_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('completed', 'Effectué'), ('cancelled', 'Annulé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
    ]
