# Generated by Django 5.2 on 2025-11-09 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_donorranking_hospitalbenefit_donorvoucher'),
    ]

    operations = [
    ]
