# Generated by Django 5.2.5 on 2025-09-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hospital_type',
            field=models.CharField(blank=True, choices=[('public', 'Hôpital public'), ('private', 'Clinique privée'), ('chu', 'CHU (Centre Hospitalier Universitaire)'), ('military', 'Hôpital militaire'), ('other', 'Autre')], max_length=50),
        ),
    ]
