# Generated by Django 5.2.5 on 2025-09-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donationresponse_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('completed', 'Terminé'), ('unsatisfied', 'Insatisfait')], default='pending', max_length=20),
        ),
    ]
