# Generated by Django 5.2 on 2025-11-09 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_bloodrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_donations', models.PositiveIntegerField(default=0, help_text='Nombre total de dons complétés')),
                ('current_tier', models.CharField(choices=[('standard', 'Standard'), ('bronze', 'Bronze'), ('silver', 'Argent'), ('gold', 'Or'), ('platinum', 'Platine')], default='standard', max_length=20)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0, help_text='Points cumulés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.OneToOneField(limit_choices_to={'user_type': 'donor'}, on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classement Donneur',
                'verbose_name_plural': 'Classements Donneurs',
                'ordering': ['-total_donations', '-points'],
            },
        ),
        migrations.CreateModel(
            name='HospitalBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Consultation gratuite', max_length=200)),
                ('description', models.TextField()),
                ('minimum_tier', models.CharField(choices=[('standard', 'Standard'), ('bronze', 'Bronze'), ('silver', 'Argent'), ('gold', 'Or'), ('platinum', 'Platine')], default='bronze', max_length=20)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Pourcentage de réduction (0-100)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(limit_choices_to={'user_type': 'hospital'}, on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avantage Hôpital',
                'verbose_name_plural': 'Avantages Hôpitaux',
                'ordering': ['-discount_percentage'],
            },
        ),
        migrations.CreateModel(
            name='DonorVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=20, unique=True)),
                ('discount_percentage', models.PositiveIntegerField()),
                ('valid_until', models.DateField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(limit_choices_to={'user_type': 'donor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(limit_choices_to={'user_type': 'hospital'}, on_delete=django.db.models.deletion.CASCADE, related_name='issued_vouchers', to=settings.AUTH_USER_MODEL)),
                ('benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.hospitalbenefit')),
            ],
            options={
                'verbose_name': 'Bon de Réduction',
                'verbose_name_plural': 'Bons de Réduction',
                'ordering': ['-created_at'],
            },
        ),
    ]
