# Generated by Django 5.2.5 on 2025-09-07 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_donation',
        ),
        migrations.AddField(
            model_name='customuser',
            name='hospital_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de licence hôpital'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hospital_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de vérification (admin)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'En attente de vérification'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut de vérification'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='medical_history',
            field=models.TextField(blank=True, null=True, verbose_name='Antécédents médicaux'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('donor', 'Donneur'), ('hospital', 'Hôpital')], max_length=10),
        ),
    ]
